name: Changelog

on:
  pull_request:
  push:
    branches:
      - master
      - terraform-0.11.x/master
    paths-ignore: ["CHANGELOG.md"]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.AUTOMATION_REPO_TOKEN }}

      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          excludeTagsRegex: '^v\d+(\.\d+)?$'
          token: ${{ github.token }}
          onlyLastTag: false
          stripHeaders: false
          stripGeneratorNotice: true
          pullRequests: false
          unreleased: true
          issues: true
          prWoLabels: false
          issuesWoLabels: true
          addSections: '{"documentation":{"prefix":"**Documentation:**","labels":["documentation"]}}'

      - id: comment
        if: ${{ github.event.pull_request }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          : Post Changelog to Pull-Request
          sh gh-issue-comment.sh --comment-id 'changelog' 'CHANGELOG.md' "${{ github.event.pull_request.number }}"

      - if: ${{ github.ref_protectect }}
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMATION_REPO_TOKEN }}
        run: |
          : Disable branch protections
          gh api -XDELETE 'repos/{owner}/{repo}/branches/${{ github.ref_name }}/protection/enforce_admins'

      - id: push-changelog
        if: ${{ steps.settings.outputs.protected == 'true' }}
        run: |
          : Push Changelog
          set -e
          git config user.name 'Automatic Changelog'
          git config user.email '<github-actions@users.noreply.github.com>'
          tac CHANGELOG.md | awk 'NF {p=1} p' | tac > CHANGELOG.new
          mv CHANGELOG.new CHANGELOG.md
          git add CHANGELOG.md
          git commit -m 'Update Changelog' || :
          git push

      - if: ${{ always() && steps.settings.outputs.protected == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMATION_REPO_TOKEN }}
        run: |
          : Enable branch protections
          gh api -XPOST 'repos/{owner}/{repo}/branches/${{ github.ref_name }}/protection/enforce_admins'
