name: Pull Request

on: [pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3

  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: template
      run: |
        : Template File
        cat>.comment.md<<END_OF_COMMENT
        CI/CD Comment Test
        | Issue | Submitter  |
        |:-----:|------------|
        |${{ github.event.pull_request.number }} | ${{ github.event.pull_request.user.login }} |
        END_OF_COMMENT

    - id: post
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        : Post Comment
        printf '\n:heavy_check_mark: Posted: %s\n' "$(date -u)" >> '.comment.md'
        sh gh-issue-comment.sh --comment-id 'comment-test' '.comment.md' "${{ github.event.pull_request.number }}"

    - id: update
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        : Update Comment
        printf '\n:heavy_check_mark: Updated: %s\n' "$(date -u)" >> '.comment.md'
        sh gh-issue-comment.sh --comment-id 'comment-test' '.comment.md' "${{ github.event.pull_request.number }}"

    - id: upload
      uses: actions/upload-artifact@v3
      with:
        name: comment
        path: .comment.md

  issue-resolution:
    name: Validate Issue Resolution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: issue-resolution
      run: |
        : Validate commit is resolving an issue
        die() { echo "$*" >&2; exit 1; }
        set -- $(gh api "repos/{owner}/{repo}/pulls/${{ github.event.pull_request.number }}/commits" --jq '.[].sha')
        git fetch --deepen=${#}
        for sha; do
          git show -s --format='%s%n%n%b' "${sha}" > '/tmp/git-commit-message.log'
          title="$(grep -Pzo '^.+(?=\n\n)' < '/tmp/git-commit-message.log')"
          type="$(printf '%s' "${title}" | grep -P '^\S+(?=:)')"
          test -n "${type}" || die "${sha}: title missing 'type:' prefix"
          case "${type}" in
          (fix|hotfix)  type='fix';;
          (*)           type='close';;
          esac
          footer="$(grep -Pzo '(?<=\n\n).+$' < '/tmp/git-commit-message.log')"
          test -n "${footer}" || die 'missing commit message footer'
          for resolution in $(printf '%s' "${footer}" | grep -P '(Fix(e[sd])?|Close[sd]?)(?=:.*)'); do
            case "${resolution}" in
            ([Ff]ix|[Ff]ixe[sd]) resolution='fix';;
            ([Cc]lose[sd]?)      resolution='close';;
            (*)                  die 'no valid issue resolution found in commit message footer';;
            esac
            test "${type}" = "${resolution}" || die "invalid resolution type for '${type}'"
          done
        done

  issue-status:
    name: Validate Open Issue
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: issue-status
      run: |
        : Validate closed issues are in an open state
        die() { echo "$*" >&2; exit 1; }
        set -- $(gh api "repos/{owner}/{repo}/pulls/${{ github.event.pull_request.number }}/commits" --jq '.[].sha')
        git fetch --deepen=${#}
        for sha; do
          git show -s --format='%s%n%n%b' "${sha}" > '/tmp/git-commit-message.log'
          footer="$(grep -Pzo '(?<=\n\n).+$' '/tmp/git-commit-message.log')"
          test -n "${footer}" || die 'missing commit message footer'
          footer="$(printf '%s' "${footer}" | sed -e 's,#,,g' -e 's/,/ /g')"
          set --
          set -- "${@}" $(printf '%s' "${footer}" | grep -P 'grep -Poz '(?<=[Ff]ixe[sd]:\s).+')
          set -- "${@}" $(printf '%s' "${footer}" | grep -P 'grep -Poz '(?<=[Ff]ix:\s).+')
          set -- "${@}" $(printf '%s' "${footer}" | grep -P 'grep -Poz '(?<=Close:\s).+')
          set -- "${@}" $(printf '%s' "${footer}" | grep -P 'grep -Poz '(?<=Close[sd]:\s).+')
          unset footer
          for issue; do
            state="gh api "repos/{owner}/{repo}/issues/${issue}" --jq '.state'> /dev/null 2>&1)"
            test -n "${state}" || die "invalid issue '${issue}'"
            test "${state}" = 'open' || die "issue '${issue}' already closed"
          done
        done
