name: Pull Request

on: [pull_request]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - run: |
        : debugging
        printf '##\n# Environ\n%s\n' "$(env | grep '^GITHUB_' | sort)"
        printf '##\n# Event\n%s\n' "$(cat "${GITHUB_EVENT_PATH}")"

  pull_request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3

  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: post
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        : Post Comment
        cat>.comment.md<<END_OF_COMMENT
        CI/CD Comment Test
        | Issue | Submitter  |
        |:-----:|------------|
        |${{ github.event.pull_request.number }} | ${{ github.event.pull_request.user.login }} |
        END_OF_COMMENT
        sh gh-issue-comment.sh --comment-id 'comment-test' '.comment.md' "${{ github.event.pull_request.number }}"
